// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/user/register.ts";
import * as $4 from "./routes/api/user/visit.ts";
import * as $5 from "./routes/dashboard.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/login.tsx";
import * as $8 from "./routes/logout.tsx";
import * as $9 from "./routes/note/index.tsx";
import * as $10 from "./routes/signup.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/NoteView.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/user/register.ts": $3,
    "./routes/api/user/visit.ts": $4,
    "./routes/dashboard.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/login.tsx": $7,
    "./routes/logout.tsx": $8,
    "./routes/note/index.tsx": $9,
    "./routes/signup.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/NoteView.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
