// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/api/user/register.ts";
import * as $2 from "./routes/api/user/visit.ts";
import * as $3 from "./routes/dashboard.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/login.tsx";
import * as $6 from "./routes/logout.tsx";
import * as $7 from "./routes/signup.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/api/user/register.ts": $1,
    "./routes/api/user/visit.ts": $2,
    "./routes/dashboard.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/login.tsx": $5,
    "./routes/logout.tsx": $6,
    "./routes/signup.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
